package test.percussion.pso.jexl;

import java.text.ParseException;
import java.util.Calendar;

import org.junit.Test;

import com.percussion.pso.jexl.PSODateTools;
import junit.framework.TestCase;

/**
 * The class <code>PSODateToolsTest</code> contains tests for the class {@link
 * <code>PSODateTools</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 10/5/10 3:55 PM
 *
 * @author natechadwick
 *
 * @version $Revision$
 */
public class PSODateToolsTest extends TestCase {

	public PSODateToolsTest(){}
	
	/**
	 * Run the String formatDate(String, Object) method test
	 */
	@Test
	public void testFormatDate() throws ParseException{
		// add test code here
		PSODateTools fixture = new PSODateTools();
		String format = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";
		Object date_value = Calendar.getInstance().getTime();
		String result = fixture.formatDate(format, date_value);
		assertTrue(result=="");
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = formatDate(QString;!QObject;)
 * package = test.percussion.pso
 * package.sourceFolder = PSOToolkit66/src
 * superclassType = junit.framework.TestCase
 * testCase = PSODateToolsTest
 * testClassType = com.percussion.pso.jexl.PSODateTools
 */